"use client"

import { FormEvent, useState } from "react"
import { useParams, useRouter } from "next/navigation"

export default function ResetPasswordPage(){
  const {token}=useParams<{token:string}>();const router=useRouter();const [password,setPassword]=useState("");const [confirm,setConfirm]=useState("");const [error,setError]=useState("");const [busy,setBusy]=useState(false)
  async function submit(event:FormEvent){event.preventDefault();if(password!==confirm){setError("Passwords do not match");return}setBusy(true);setError("");const response=await fetch("/api/auth/reset/complete",{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({token,password})});const data=await response.json();if(response.ok)router.replace("/auth/sign-in?reset=complete");else setError(data.error||"Unable to reset password");setBusy(false)}
  return <main className="admin-shell flex min-h-screen items-center justify-center px-4"><section className="admin-material w-full max-w-sm rounded-3xl p-8"><h1 className="text-2xl font-bold tracking-tight">Choose a new password</h1><p className="mb-6 mt-1 text-sm text-muted-foreground">Use at least 10 characters.</p><form onSubmit={submit} className="space-y-4"><div><label className="mb-1.5 block text-sm font-medium" htmlFor="password">New password</label><input id="password" type="password" autoComplete="new-password" minLength={10} className="admin-field h-11 w-full rounded-xl px-4 outline-none focus-visible:ring-2 focus-visible:ring-ring" value={password} onChange={e=>setPassword(e.target.value)} required /></div><div><label className="mb-1.5 block text-sm font-medium" htmlFor="confirm">Confirm password</label><input id="confirm" type="password" autoComplete="new-password" minLength={10} className="admin-field h-11 w-full rounded-xl px-4 outline-none focus-visible:ring-2 focus-visible:ring-ring" value={confirm} onChange={e=>setConfirm(e.target.value)} required /></div>{error&&<p className="text-sm text-destructive" role="alert">{error}</p>}<button disabled={busy} className="admin-primary-button h-11 w-full rounded-xl text-sm font-medium text-white disabled:opacity-50">{busy?"Updating…":"Update password"}</button></form></section></main>
}
